apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{MODULE}}-deployment
  namespace: tawa
  labels:
    app: {{MODULE}}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{MODULE}}-app
  template:
    metadata:
      labels:
        app: {{MODULE}}-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: {{MODULE}}-service
          image: {{IMAGE_NAME}}
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
          

      nodeSelector:
        kubernetes.io/os: linux
