apiVersion: v1
kind: Service
metadata:
  name: {{MODULE}}-service
  namespace: tawa
  labels:
    app: {{MODULE}}-app
spec:
  selector:
    app: {{MODULE}}-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP